#!/usr/bin/python3
from parse import *
from math import exp


try:
    args = parse_arguments()
except:
    exit(84)


def formula(a, t):
    return a * exp(-t) + (4 - 3 * a) * exp(-2 * t) + (2 * a - 4) * exp(-4 * t)


print(args.a)
print(formula(args.a, 0))
print(formula(args.a, 0.2))
print(formula(args.a, 0.5))
print(formula(args.a, 1))
print(formula(args.a, 2))